---
title: "Lab7"
author: Jesse and Ryan
output: html_notebook
---
GitHub URL: https://github.com/s1075803/lab7

## 2
The quiz grades seem to have a weak positive association with each other. There is an association because the grades are 
```{r}
plot(quiz)
```
## 3
```{r}
plot(quiz$Q2,quiz$Q6)
```
## 4
Yes the Pearson Correlation test shows a positive correlation between Quiz 2 and 6. 
```{r}
cor(quiz$Q2, quiz$Q6)
```
## 5
```{r}
single.boot<-function(x, y){
  indicies<-sample(length(x), replace=TRUE)
  boot.corr<-cor(x[indicies], y[indicies])
  return(boot.corr)
}
single.boot(quiz$Q2, quiz$Q6)
```
```{r}
bootstrap.cor<-function(x,y,B=2000){
correlation<-replicate(B, single.boot(x,y))
return(correlation)
}
#bootstrap.cor(quiz$Q2, quiz$Q6)
```

## 6
```{r}
estimate<-bootstrap.cor(x=quiz$Q2, y=quiz$Q6, B=5000)
hist(estimate)
```
## 7 
```{r}
quantile(estimate, c(0.025,0.975))
test<-cor.test(x=quiz$Q2, y=quiz$Q6,conf.level = 0.95)
test$conf
```

## 8
```{r}
cov1<-cov(quiz)
cov1[1,5]
cov(quiz$Q2, quiz$Q6)

```

## 9
They are in decreasing order.
```{r}
eigen.vals<-eigen(cov1)$values
eigen.vals
```

## 10
```{r}
sum(eigen.vals)
sum(diag(cov1))
```

## 11
```{r}
eigen.vals[1]/sum(eigen.vals)
```

## 12
```{r}

```

